/* Phrases for «повторяй». kind: 'word' | 'sentence'. Curated by theme.
   No native-speaker review has been done on this list; the earlier claim of
   one was removed rather than left sitting in a public repo. */
window.PHRASES = [
  { ru: "дом", en: "house", kind: "word", translit: "dom" },
  { ru: "вода", en: "water", kind: "word", translit: "vada" },
  { ru: "хлеб", en: "bread", kind: "word", translit: "khleb" },
  { ru: "друг", en: "friend", kind: "word", translit: "drug" },
  { ru: "время", en: "time", kind: "word", translit: "vremya" },
  { ru: "день", en: "day", kind: "word", translit: "den" },
  { ru: "книга", en: "book", kind: "word", translit: "kniga" },
  { ru: "деньги", en: "money", kind: "word", translit: "dengi" },
  { ru: "город", en: "city", kind: "word", translit: "gorat" },
  { ru: "мама", en: "mom", kind: "word", translit: "mama" },
  { ru: "знать", en: "to know", kind: "word", translit: "znat" },
  { ru: "говорить", en: "to speak", kind: "word", translit: "gavarit" },
  { ru: "хотеть", en: "to want", kind: "word", translit: "khatet" },
  { ru: "делать", en: "to do", kind: "word", translit: "delat" },
  { ru: "идти", en: "to go", kind: "word", translit: "idti" },
  { ru: "есть", en: "to eat", kind: "word", translit: "yest" },
  { ru: "пить", en: "to drink", kind: "word", translit: "pit" },
  { ru: "работать", en: "to work", kind: "word", translit: "rabotat" },
  { ru: "думать", en: "to think", kind: "word", translit: "dumat" },
  { ru: "жить", en: "to live", kind: "word", translit: "zhit" },
  { ru: "большой", en: "big", kind: "word", translit: "balshoy" },
  { ru: "хороший", en: "good", kind: "word", translit: "kharoshiy" },
  { ru: "новый", en: "new", kind: "word", translit: "novyy" },
  { ru: "красивый", en: "beautiful", kind: "word", translit: "krasivyy" },
  { ru: "один", en: "one", kind: "word", translit: "adin" },
  { ru: "два", en: "two", kind: "word", translit: "dva" },
  { ru: "три", en: "three", kind: "word", translit: "tri" },
  { ru: "пять", en: "five", kind: "word", translit: "pyat" },
  { ru: "понедельник", en: "monday", kind: "word", translit: "panedelnik" },
  { ru: "суббота", en: "saturday", kind: "word", translit: "subbota" },
  { ru: "спасибо", en: "thank you", kind: "word", translit: "spasiba" },
  { ru: "привет", en: "hi", kind: "word", translit: "privet" },
  { ru: "Здравствуйте, рад вас видеть.", en: "hello, glad to see you.", kind: "sentence", translit: "zdravstvuyte, rad vas videt" },
  { ru: "Привет, как дела?", en: "hi, how are you?", kind: "sentence", translit: "privet, kak dela" },
  { ru: "Доброе утро!", en: "good morning!", kind: "sentence", translit: "dobroye utra" },
  { ru: "Добрый вечер!", en: "good evening!", kind: "sentence", translit: "dobryy vecher" },
  { ru: "Меня зовут Анна.", en: "my name is anna.", kind: "sentence", translit: "menya zavut anna" },
  { ru: "Очень приятно познакомиться.", en: "very nice to meet you.", kind: "sentence", translit: "ochen priyatna paznakomitsa" },
  { ru: "Как вас зовут?", en: "what is your name?", kind: "sentence", translit: "kak vas zavut" },
  { ru: "Спасибо большое за помощь.", en: "thank you very much for the help.", kind: "sentence", translit: "spasiba balshoye za pomashch" },
  { ru: "Пожалуйста, не за что.", en: "you're welcome, don't mention it.", kind: "sentence", translit: "pazhalusta, ne za shta" },
  { ru: "Извините, я не понял.", en: "sorry, i didn't understand.", kind: "sentence", translit: "izvinite, ya ne ponyal" },
  { ru: "Прошу прощения за опоздание.", en: "i'm sorry for being late.", kind: "sentence", translit: "prashu prashcheniya za apazdaniye" },
  { ru: "До свидания, всего доброго!", en: "goodbye, all the best!", kind: "sentence", translit: "da svidaniya, vsevo dobrava" },
  { ru: "Увидимся завтра!", en: "see you tomorrow!", kind: "sentence", translit: "uvidimsya zavtra" },
  { ru: "У меня всё хорошо, спасибо.", en: "i'm doing well, thank you.", kind: "sentence", translit: "u menya vsyo kharasho, spasiba" },
  { ru: "Будьте добры, помогите мне.", en: "please be so kind, help me.", kind: "sentence", translit: "budte dabry, pamagite mne" },
  { ru: "Я хотел бы кофе, пожалуйста.", en: "i would like a coffee, please.", kind: "sentence", translit: "ya khatel by kofe, pazhalusta" },
  { ru: "Мне нужна помощь.", en: "i need help.", kind: "sentence", translit: "mne nuzhna pomashch" },
  { ru: "Где здесь туалет?", en: "where is the toilet here?", kind: "sentence", translit: "gde zdes tualet" },
  { ru: "Я не понимаю.", en: "i don't understand.", kind: "sentence", translit: "ya ne panimayu" },
  { ru: "Говорите медленнее, пожалуйста.", en: "speak slower, please.", kind: "sentence", translit: "gavarite medlenneye, pazhalusta" },
  { ru: "Сколько это стоит?", en: "how much does this cost?", kind: "sentence", translit: "skolka eta stoit" },
  { ru: "Можно меню, пожалуйста?", en: "can i have the menu, please?", kind: "sentence", translit: "mozhna menyu, pazhalusta" },
  { ru: "Повторите, пожалуйста.", en: "please repeat that.", kind: "sentence", translit: "paftarite, pazhalusta" },
  { ru: "Мне нужно такси.", en: "i need a taxi.", kind: "sentence", translit: "mne nuzhna taksi" },
  { ru: "Где находится вокзал?", en: "where is the train station?", kind: "sentence", translit: "gde nakhoditsa vakzal" },
  { ru: "Я хочу пить.", en: "i'm thirsty.", kind: "sentence", translit: "ya khachu pit" },
  { ru: "Помогите мне, пожалуйста.", en: "help me, please.", kind: "sentence", translit: "pamagite mne, pazhalusta" },
  { ru: "Вы говорите по-английски?", en: "do you speak english?", kind: "sentence", translit: "vy gavarite pa-angliyski" },
  { ru: "Дайте счёт, пожалуйста.", en: "the bill, please.", kind: "sentence", translit: "dayte shchyot, pazhalusta" },
  { ru: "Я ищу аптеку.", en: "i'm looking for a pharmacy.", kind: "sentence", translit: "ya ishchu apteku" },
  { ru: "Как тебя зовут?", en: "what is your name?", kind: "sentence", translit: "kak tebya zavut" },
  { ru: "Ты говоришь по-английски?", en: "do you speak english?", kind: "sentence", translit: "ty gavarish pa-angliyski" },
  { ru: "Который сейчас час?", en: "what time is it?", kind: "sentence", translit: "katoryy seychas chas" },
  { ru: "Как дела?", en: "how are you?", kind: "sentence", translit: "kak dela" },
  { ru: "Что ты сейчас делаешь?", en: "what are you doing right now?", kind: "sentence", translit: "shto ty seychas delayesh" },
  { ru: "Куда ты идёшь?", en: "where are you going?", kind: "sentence", translit: "kuda ty idyosh" },
  { ru: "Когда ты приедешь?", en: "when will you arrive?", kind: "sentence", translit: "kagda ty priyedesh" },
  { ru: "Почему ты опоздал?", en: "why are you late?", kind: "sentence", translit: "pachemu ty apazdal" },
  { ru: "Как пройти в центр?", en: "how do i get to the center?", kind: "sentence", translit: "kak prayti v tsentr" },
  { ru: "Сколько тебе лет?", en: "how old are you?", kind: "sentence", translit: "skolka tebe let" },
  { ru: "Откуда ты приехал?", en: "where did you come from?", kind: "sentence", translit: "atkuda ty priyekhal" },
  { ru: "Что это такое?", en: "what is this?", kind: "sentence", translit: "shto eta takoye" },
  { ru: "Можно мне немного воды?", en: "can i have some water?", kind: "sentence", translit: "mozhna mne nemnoga vady" },
  { ru: "Один кофе, пожалуйста.", en: "one coffee, please.", kind: "sentence", translit: "adin kofe, pazhalusta" },
  { ru: "У вас есть свободный столик?", en: "do you have a free table?", kind: "sentence", translit: "u vas yest svabodnyy stolik" },
  { ru: "Я хочу чай с лимоном.", en: "i want tea with lemon.", kind: "sentence", translit: "ya khachu chay s limonam" },
  { ru: "Дайте, пожалуйста, воду.", en: "give me some water, please.", kind: "sentence", translit: "dayte, pazhalusta, vodu" },
  { ru: "Это очень вкусно, спасибо.", en: "this is very tasty, thank you.", kind: "sentence", translit: "eta ochen vkusna, spasiba" },
  { ru: "Как пройти к вокзалу?", en: "how do i get to the station?", kind: "sentence", translit: "kak prayti k vakzalu" },
  { ru: "Один билет, пожалуйста.", en: "one ticket, please.", kind: "sentence", translit: "adin bilet, pazhalusta" },
  { ru: "Сколько стоит билет?", en: "how much is the ticket?", kind: "sentence", translit: "skolka stoit bilet" },
  { ru: "Как доехать до центра?", en: "how do i get to the center?", kind: "sentence", translit: "kak dayekhat da tsentra" },
  { ru: "Где ближайшая станция метро?", en: "where is the nearest metro station?", kind: "sentence", translit: "gde blizhayshaya stantsiya metro" },
  { ru: "Во сколько отходит поезд?", en: "what time does the train leave?", kind: "sentence", translit: "va skolka atkhodit poyezd" },
  { ru: "Мне нужен номер на двоих.", en: "i need a room for two.", kind: "sentence", translit: "mne nuzhen nomer na dvaikh" },
  { ru: "Мне это очень нравится.", en: "i really like it.", kind: "sentence", translit: "mne eta ochen nravitsa" },
  { ru: "Я немного устал сегодня.", en: "i am a little tired today.", kind: "sentence", translit: "ya nemnoga ustal sivodnya" },
  { ru: "Это очень интересно.", en: "that is very interesting.", kind: "sentence", translit: "eta ochen interesna" },
  { ru: "Я тоже так думаю.", en: "i think so too.", kind: "sentence", translit: "ya tozhe tak dumayu" },
  { ru: "Сегодня прекрасная погода.", en: "the weather is lovely today.", kind: "sentence", translit: "sivodnya prekrasnaya pagoda" },
  { ru: "На улице идёт дождь.", en: "it is raining outside.", kind: "sentence", translit: "na ulitse idyot dozhd" },
  { ru: "Я очень рад тебя видеть.", en: "i am very glad to see you.", kind: "sentence", translit: "ya ochen rad tibya videt" },
  { ru: "Как у тебя дела?", en: "how are you doing?", kind: "sentence", translit: "kak u tibya dela" },
  { ru: "Мне немного грустно.", en: "i feel a little sad.", kind: "sentence", translit: "mne nemnoga grustna" },
  { ru: "Это отличная идея.", en: "that is a great idea.", kind: "sentence", translit: "eta atlichnaya ideya" },
  { ru: "Я совсем не согласен.", en: "i do not agree at all.", kind: "sentence", translit: "ya savsem ne saglasen" },
  { ru: "Сегодня очень холодно.", en: "it is very cold today.", kind: "sentence", translit: "sivodnya ochen kholadna" },
  { ru: "Я так устал от работы.", en: "i am so tired from work.", kind: "sentence", translit: "ya tak ustal at raboty" },
];
